name: mlops_env
channels:
  - defaults
dependencies:
  - attrs=23.1.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - cachecontrol=0.12.11
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - cleo=2.0.1
  - colorama=0.4.6
  - crashtest=0.4.1
  - cryptography=41.0.7
  - dulwich=0.21.3
  - filelock=3.13.1
  - html5lib=1.1
  - idna=3.4
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - intel-openmp=2023.1.0
  - jaraco.classes=3.2.1
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - keyring=23.13.1
  - libffi=3.4.4
  - lockfile=0.12.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - more-itertools=10.1.0
  - msgpack-python=1.0.3
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openssl=3.0.12
  - pexpect=4.8.0
  - pip=23.3.1
  - pkginfo=1.9.6
  - poetry=1.4.0
  - poetry-core=1.5.1
  - poetry-plugin-export=1.3.0
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyproject_hooks=1.0.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-build=0.10.0
  - python-installer=0.6.0
  - pywin32-ctypes=0.2.0
  - rapidfuzz=2.13.7
  - referencing=0.30.2
  - requests=2.31.0
  - requests-toolbelt=0.9.1
  - rpds-py=0.10.6
  - shellingham=1.5.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tomli=2.0.1
  - tomlkit=0.11.1
  - trove-classifiers=2023.10.18
  - tzdata=2023d
  - urllib3=1.26.18
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - webencodings=0.5.1
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - xz=5.4.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - black==23.12.1
      - cfgv==3.4.0
      - click==8.1.7
      - distlib==0.3.8
      - flake8==7.0.0
      - identify==2.5.33
      - isort==5.13.2
      - mccabe==0.7.0
      - mypy-extensions==1.0.0
      - nodeenv==1.8.0
      - packaging==23.2
      - pathspec==0.12.1
      - platformdirs==4.1.0
      - pre-commit==3.6.0
      - pycodestyle==2.11.1
      - pyflakes==3.2.0
      - pyyaml==6.0.1
      - setuptools==69.0.3
      - typing-extensions==4.9.0
      - virtualenv==20.25.0
